//lib/country-data.ts
export type CountryLocale = 'en' | 'ar' | 'tr';

export interface CountryFAQ {
  question: string;
  answer:   string;
}

export interface CountryLocaleData {
  language:     string;
  dir:          'ltr' | 'rtl';
  locale:       string;
  whyUs?:       string;
  metaTitle:    string;
  metaDescription: string;
  heroBadge:    string;
  heroH1:       string;
  heroSubtitle: string;
  heroPriceNote: string;
  ctaPrimaryText:   string;
  ctaSecondaryText: string;
  seoIntro:     string;
  trustPoints:  string[];
  faq:          CountryFAQ[];
}

export interface CountryData {
  countryName:  string;
  countryCode:  string;
  slug:         string;
  locale:       string;
  language:     string;
  dir:          'ltr' | 'rtl';
  dialCode:     string;
  geoPosition:  string; // "lat;lng"
  metaTitle:    string;
  metaDescription: string;
  metaKeywords: string;
  heroBadge:    string;
  heroH1:       string;
  heroSubtitle: string;
  heroPriceNote: string;
  ctaPrimaryText:   string;
  ctaSecondaryText: string;
  seoIntro:     string;
  trustPoints:  string[];
  faq:          CountryFAQ[];
  ar:           CountryLocaleData;
  tr?:          CountryLocaleData; // Turkey only
}

export const COUNTRIES_DATA: Record<string, CountryData> = {
  eg: {
    countryName: 'Egypt', countryCode: 'EG', slug: 'eg',
    locale: 'ar_EG', language: 'en', dir: 'ltr',
    dialCode: '+20', geoPosition: '26.8206;30.8025',
    metaTitle: 'WhatsApp API Egypt | أرخص WhatsApp OTP API في مصر $10/شهر غير محدود | Nabda OTP',
    metaDescription: 'Nabda OTP – أرخص WhatsApp API في مصر. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، 5 أيام مجانية. أفضل بديل Twilio وUltraMsg للشركات المصرية. يدعم أرقام +20.',
    metaKeywords: 'whatsapp api egypt, whatsapp otp egypt, ارخص واتساب api مصر, otp api مصر, nabda otp egypt, twilio alternative egypt',
    heroBadge: 'The most reliable WhatsApp verification platform',
    heroH1: 'The Cheapest & First WhatsApp Gateway in Egypt & MENA Region.',
    heroSubtitle: 'Send unlimited OTPs through our WhatsApp Gateway. The cheapest, most reliable API solution for developers and businesses in Egypt.',
    heroPriceNote: 'Starting at just <strong>$10/month</strong> — No per-message fees',
    ctaPrimaryText: 'Start Free Trial', ctaSecondaryText: 'View Documentation',
    seoIntro: 'Nabda OTP helps businesses in Egypt ship WhatsApp OTP and transactional messaging quickly with clean API workflows and regional support.',
    trustPoints: ['65+ Businesses Trust Us', '4500+ Messages Sent', '99.99% Uptime Guaranteed', 'Most Reliable in MENA'],
    faq: [
      { question: 'What is the cheapest WhatsApp API in Egypt in 2026?', answer: 'Nabda OTP at only $10/month for unlimited messages with no per-message fees — up to 90% cheaper than Twilio or UltraMsg.' },
      { question: 'Does Nabda OTP support Egyptian phone numbers +20?', answer: 'Yes, all Egyptian numbers (+20) across Vodafone, Orange, Etisalat, and WE.' },
      { question: 'Is there a free trial for WhatsApp API in Egypt?', answer: 'Yes, a full 5-day free trial with no credit card required.' },
      { question: 'Is Nabda OTP better than Twilio or UltraMsg in Egypt?', answer: 'Yes — saves up to 90% with unlimited messages, instant webhook, and full Arabic support.' },
      { question: 'Does Nabda OTP support sending images and documents?', answer: 'Yes — text, images, videos, PDF documents and more.' },
      { question: 'What is the difference between Standard Gateway and Official API?', answer: 'Standard ($10/mo unlimited) suits most developers and SMBs. Official is for large enterprises needing the Green Badge.' },
    ],
    ar: {
      language: 'ar', dir: 'rtl', locale: 'ar_EG',
      metaTitle: 'WhatsApp API مصر | أرخص خدمة OTP واتساب في مصر | Nabda OTP',
      metaDescription: 'نبضة OTP في مصر: واتساب API بسعر 10 دولار شهريا مع رسائل غير محدودة، ويبهوك، دعم عربي، وتجربة مجانية 5 أيام.',
      heroBadge: 'منصة موثوقة للتحقق عبر واتساب',
      heroH1: 'أرخص وأول بوابة واتساب في مصر ومنطقة الشرق الأوسط وشمال أفريقيا.',
      heroSubtitle: 'أرسل عددًا غير محدود من رموز التحقق OTP عبر بوابة واتساب الخاصة بنا. الحل الأمثل والأكثر موثوقية للمطورين والشركات في مصر.',
      heroPriceNote: 'ابدأ من <strong>10$ شهرياً</strong> بدون رسوم لكل رسالة',
      ctaPrimaryText: 'ابدأ التجربة المجانية', ctaSecondaryText: 'عرض التوثيق',
      seoIntro: 'نبضة OTP تساعد الشركات في مصر على إطلاق OTP وإشعارات واتساب بسرعة مع تكامل API واضح.',
      trustPoints: ['موثوق من شركات في مصر', 'إرسال سريع وموثوق', 'دعم عربي كامل', 'توفر 99.99%'],
      faq: [
        { question: 'ما هو أرخص WhatsApp API في مصر 2026؟', answer: 'نبضة OTP بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة، بدون رسوم لكل رسالة. يوفر حتى 90% مقارنة بالمنافسين.' },
        { question: 'هل Nabda OTP يدعم أرقام الهواتف المصرية +20؟', answer: 'نعم، يدعم جميع أرقام مصر (+20) عبر شبكات فودافون، أورانج، اتصالات، WE.' },
        { question: 'هل يوجد تجربة مجانية لـ WhatsApp API في مصر؟', answer: 'نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان.' },
        { question: 'هل Nabda OTP بديل جيد لـ Twilio أو UltraMsg في مصر؟', answer: 'نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة، webhook فوري، ودعم عربي كامل.' },
        { question: 'هل يدعم Nabda OTP إرسال الصور والمستندات؟', answer: 'نعم، يدعم الرسائل النصية والصور والفيديوهات ومستندات PDF وغيرها.' },
        { question: 'ما الفرق بين الـ Standard Gateway والـ Official API؟', answer: 'الـ Standard (10$ غير محدود) مناسب لمعظم الشركات. الـ Official للشركات الكبرى التي تحتاج Green Badge.' },
      ],
    },
  },
  iq: {
    countryName: 'Iraq', countryCode: 'IQ', slug: 'iq',
    locale: 'ar_IQ', language: 'en', dir: 'ltr',
    dialCode: '+964', geoPosition: '33.2232;43.6793',
    metaTitle: 'WhatsApp API Iraq | أرخص WhatsApp OTP API في العراق $10/شهر غير محدود | Nabda OTP',
    metaDescription: 'Nabda OTP – أرخص WhatsApp API في العراق. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +964.',
    metaKeywords: 'whatsapp api iraq, whatsapp otp iraq, ارخص واتساب api العراق, otp api العراق, nabda otp iraq, twilio alternative iraq',
    heroBadge: 'The most reliable WhatsApp verification platform in Iraq',
    heroH1: 'The Cheapest & First WhatsApp Gateway in Iraq & MENA Region.',
    heroSubtitle: 'Send unlimited OTPs through our WhatsApp Gateway. The cheapest, most reliable API for developers and businesses in Iraq.',
    heroPriceNote: 'Starting at just <strong>$10/month</strong> — No per-message fees',
    ctaPrimaryText: 'Start Free Trial', ctaSecondaryText: 'View Documentation',
    seoIntro: 'Nabda OTP helps Iraqi businesses and developers launch fast and affordable WhatsApp OTP with clean API workflows and strong local delivery.',
    trustPoints: ['Reliable delivery across all Iraqi networks', 'Optimized for the Iraqi market', 'Full Arabic support', '99.99% Uptime Guaranteed'],
    faq: [
      { question: 'What is the cheapest WhatsApp API in Iraq in 2026?', answer: 'Nabda OTP at only $10/month for unlimited messages — no per-message fees. Up to 90% cheaper than alternatives.' },
      { question: 'Does Nabda OTP support Iraqi phone numbers +964?', answer: 'Yes, all Iraqi numbers (+964) across Zain, Asia Cell, Korek, and MTN.' },
      { question: 'Is there a free trial for WhatsApp API in Iraq?', answer: 'Yes, a full 5-day free trial with no credit card required.' },
      { question: 'Is Nabda OTP better than Twilio in Iraq?', answer: 'Yes — saves up to 90% with unlimited messages and full Arabic support.' },
      { question: 'Does Nabda OTP support sending images and documents?', answer: 'Yes — text, images, videos, PDF documents and more.' },
      { question: 'What is the difference between Standard Gateway and Official API?', answer: 'Standard ($10/mo unlimited) suits most developers. Official is for enterprises needing the Green Badge.' },
    ],
    ar: {
      language: 'ar', dir: 'rtl', locale: 'ar_IQ',
      metaTitle: 'WhatsApp API العراق | أرخص خدمة OTP واتساب في العراق $10/شهر | Nabda OTP',
      metaDescription: 'نبضة OTP في العراق: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، دعم عربي، وتجربة مجانية 5 أيام. يدعم أرقام +964.',
      heroBadge: 'أقوى منصة تحقق عبر واتساب في العراق',
      heroH1: 'أرخص وأول بوابة واتساب في العراق ومنطقة الشرق الأوسط وشمال أفريقيا.',
      heroSubtitle: 'أرسل عددًا غير محدود من رموز التحقق OTP عبر بوابة واتساب. الحل الأمثل والأكثر موثوقية للمطورين والشركات في العراق.',
      heroPriceNote: 'ابدأ من <strong>10$ شهرياً</strong> بدون رسوم لكل رسالة',
      ctaPrimaryText: 'ابدأ التجربة المجانية', ctaSecondaryText: 'عرض التوثيق',
      seoIntro: 'نبضة OTP تساعد الشركات والمطورين العراقيين على إطلاق OTP بتكلفة منخفضة جداً وتكامل API سهل مع أداء قوي داخل العراق.',
      trustPoints: ['توصيل موثوق عبر جميع الشبكات العراقية', 'مُحسّن للسوق العراقي', 'دعم عربي كامل', 'توفر 99.99%'],
      faq: [
        { question: 'ما هو أرخص WhatsApp API في العراق 2026؟', answer: 'نبضة OTP بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة، بدون رسوم لكل رسالة.' },
        { question: 'هل Nabda OTP يدعم أرقام الهواتف العراقية +964؟', answer: 'نعم، يدعم جميع أرقام العراق (+964) عبر شبكات زين، أسيا سيل، كورك، وموبايل تيليكوم.' },
        { question: 'هل يوجد تجربة مجانية في العراق؟', answer: 'نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان.' },
        { question: 'هل Nabda OTP بديل جيد لـ Twilio في العراق؟', answer: 'نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل.' },
        { question: 'هل يدعم إرسال الصور والمستندات؟', answer: 'نعم، يدعم النصوص والصور والفيديوهات ومستندات PDF وغيرها.' },
        { question: 'ما الفرق بين Standard وOfficial API؟', answer: 'الـ Standard (10$ غير محدود) لمعظم الشركات. الـ Official للشركات الكبرى التي تحتاج Green Badge.' },
      ],
    },
  },
  sa: {
    countryName: 'Saudi Arabia', countryCode: 'SA', slug: 'sa',
    locale: 'ar_SA', language: 'en', dir: 'ltr',
    dialCode: '+966', geoPosition: '23.8859;45.0792',
    metaTitle: 'WhatsApp API Saudi Arabia | أرخص WhatsApp OTP API في السعودية $10/شهر | Nabda OTP',
    metaDescription: 'Nabda OTP – أرخص WhatsApp API في السعودية. $10 شهرياً رسائل غير محدودة، webhook، 5 أيام مجانية، دعم عربي. أفضل بديل Twilio وUltraMsg. يدعم أرقام +966.',
    metaKeywords: 'whatsapp api saudi arabia, whatsapp otp ksa, ارخص واتساب api السعودية, nabda otp saudi, twilio alternative saudi arabia',
    heroBadge: 'The most reliable WhatsApp verification platform in KSA',
    heroH1: 'The Cheapest & First WhatsApp Gateway in Saudi Arabia & MENA Region.',
    heroSubtitle: 'Send unlimited OTPs through our WhatsApp Gateway. The most affordable, reliable solution for developers and businesses in Saudi Arabia.',
    heroPriceNote: 'Starting at just <strong>$10/month</strong> — No per-message fees',
    ctaPrimaryText: 'Start Free Trial', ctaSecondaryText: 'View Documentation',
    seoIntro: 'Nabda OTP helps businesses in Saudi Arabia ship WhatsApp OTP quickly with clean API workflows, high delivery rates, and full compliance.',
    trustPoints: ['High delivery rate across KSA networks', 'Arabic & English support', 'No per-message fees', '99.99% Uptime Guaranteed'],
    faq: [
      { question: 'What is the cheapest WhatsApp API in Saudi Arabia in 2026?', answer: 'Nabda OTP at only $10/month for unlimited messages with no per-message fees.' },
      { question: 'Does Nabda OTP support Saudi phone numbers +966?', answer: 'Yes, all Saudi numbers (+966) across STC, Mobily, and Zain.' },
      { question: 'Is there a free trial for WhatsApp API in Saudi Arabia?', answer: 'Yes, a full 5-day free trial with no credit card required.' },
      { question: 'Is Nabda OTP better than Twilio or UltraMsg in KSA?', answer: 'Yes — saves up to 90% with unlimited messages and full Arabic support.' },
      { question: 'Does Nabda OTP support media and documents?', answer: 'Yes — text, images, videos, PDF documents and more.' },
      { question: 'Standard Gateway vs Official WhatsApp Business API?', answer: 'Standard ($10/mo unlimited) suits most businesses. Official is for large enterprises needing Meta\'s Green Badge.' },
    ],
    ar: {
      language: 'ar', dir: 'rtl', locale: 'ar_SA',
      metaTitle: 'WhatsApp API السعودية | أرخص خدمة OTP واتساب في المملكة $10/شهر | Nabda OTP',
      metaDescription: 'نبضة OTP في السعودية: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، دعم عربي، وتجربة مجانية 5 أيام. يدعم أرقام +966.',
      heroBadge: 'أقوى منصة تحقق عبر واتساب في السعودية',
      heroH1: 'أرخص وأول بوابة واتساب في السعودية ومنطقة الشرق الأوسط وشمال أفريقيا.',
      heroSubtitle: 'أرسل OTP والرسائل التشغيلية عبر واتساب بلا حدود. الحل الأرخص والأكثر موثوقية للمطورين والشركات في المملكة.',
      heroPriceNote: 'ابدأ من <strong>10$ شهرياً</strong> بدون رسوم لكل رسالة',
      ctaPrimaryText: 'ابدأ التجربة المجانية', ctaSecondaryText: 'عرض التوثيق',
      seoIntro: 'نبضة OTP تساعد الشركات في السعودية على إطلاق OTP وإشعارات واتساب بسرعة عالية مع تكامل API سلس.',
      trustPoints: ['نسبة تسليم عالية عبر شبكات السعودية', 'دعم عربي وإنجليزي', 'بدون رسوم لكل رسالة', 'توفر 99.99%'],
      faq: [
        { question: 'ما هو أرخص WhatsApp API في السعودية 2026؟', answer: 'نبضة OTP بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة.' },
        { question: 'هل Nabda OTP يدعم أرقام الهواتف السعودية +966؟', answer: 'نعم، جميع أرقام السعودية (+966) عبر زين، موبايلي، STC.' },
        { question: 'هل يوجد تجربة مجانية في السعودية؟', answer: 'نعم، 5 أيام مجانية بدون بطاقة ائتمان.' },
        { question: 'هل Nabda OTP بديل جيد لـ Twilio في السعودية؟', answer: 'نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة.' },
        { question: 'هل يدعم إرسال الصور والمستندات؟', answer: 'نعم، النصوص والصور والفيديوهات ومستندات PDF وغيرها.' },
        { question: 'ما الفرق بين Standard وOfficial API؟', answer: 'الـ Standard (10$ غير محدود) لمعظم الشركات. الـ Official للشركات الكبرى.' },
      ],
    },
  },
  ae: {
    countryName: "United Arab Emirates", countryCode: "AE", slug: "ae",
    locale: "ar_AE", language: "en", dir: "ltr",
    dialCode: "+971", geoPosition: "23.4241;53.8478",
    metaTitle: "WhatsApp API UAE | أرخص WhatsApp OTP API في الإمارات $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في الإمارات العربية المتحدة. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. أفضل بديل لـ Twilio للشركات في دبي وأبوظبي. يدعم أرقام +971.",
    metaKeywords: "whatsapp api uae, whatsapp api dubai, whatsapp otp uae, ارخص واتساب api الامارات, otp api uae, nabda otp uae, whatsapp gateway dubai, twilio alternative uae, ultramsg uae, whatsapp business api uae, واتساب او تي بي الامارات, بوابة واتساب دبي",
    heroBadge: "The most reliable WhatsApp verification platform in UAE",
    heroH1: "The Cheapest & First WhatsApp Gateway in UAE & MENA Region.",
    heroSubtitle: "Send unlimited OTPs and transactional messages through our WhatsApp Gateway — Standard or Official API. The cheapest and most reliable solution for businesses and developers in the UAE.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP helps businesses in the UAE launch fast WhatsApp OTP and transactional messaging with clean API integration, high delivery rates across Etisalat and du networks, and full local support.",
    trustPoints: ["High delivery rates across UAE networks","Compliant with UAE TRA regulations","Full Arabic & English support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in the UAE in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in the UAE at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support UAE phone numbers +971?", answer: "Yes, it supports all UAE numbers (+971) with high efficiency and fast delivery across Etisalat and du networks." },
      { question: "How much does WhatsApp API cost in the UAE with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages). The Official plan is available based on your needs — contact us for details." },
      { question: "Is there a free trial for WhatsApp API in the UAE?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in the UAE?", answer: "Yes, it is the best alternative to Twilio in the UAE as it saves up to 90% on costs with unlimited messages, instant webhook, and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text messages + images + videos + PDF documents and more with ease." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_AE",
      metaTitle: "WhatsApp API الإمارات | أرخص خدمة OTP واتساب في الإمارات $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في الإمارات: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. مثالي للشركات في دبي وأبوظبي.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في الإمارات", heroH1: "أرخص وأول بوابة واتساب في الإمارات ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في الإمارات.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات في الإمارات على إطلاق OTP وإشعارات واتساب بسرعة عالية مع تكامل API سلس وامتثال للوائح المحلية.",
      trustPoints: ["نسبة تسليم عالية عبر شبكات الإمارات","متوافق مع لوائح TRA","دعم عربي وإنجليزي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في الإمارات 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في الإمارات حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة، بدون رسوم لكل رسالة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الإماراتية +971؟", answer: "نعم، يدعم جميع أرقام الإمارات (+971) بكفاءة عالية وتوصيل سريع عبر شبكات Etisalat و du." },
        { question: "كم تكلفة WhatsApp API في الإمارات مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة). الخطة المؤسسية متاحة حسب الاحتياج – تواصل معنا." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في الإمارات؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في الإمارات؟", answer: "نعم، هو أفضل بديل لـ Twilio في الإمارات لأنه يوفر حتى 90% من التكلفة مع رسائل غير محدودة، webhook فوري، ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  qa: {
    countryName: "Qatar", countryCode: "QA", slug: "qa",
    locale: "ar_QA", language: "en", dir: "ltr",
    dialCode: "+974", geoPosition: "25.3548;51.1839",
    metaTitle: "WhatsApp API Qatar | أرخص WhatsApp OTP API في قطر $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في قطر. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +974. الحل المثالي للشركات في الدوحة.",
    metaKeywords: "whatsapp api qatar, whatsapp otp qatar, ارخص واتساب api قطر, otp api قطر, nabda otp qatar, whatsapp gateway qatar, twilio alternative qatar, whatsapp business api qatar, واتساب او تي بي قطر",
    heroBadge: "The most reliable WhatsApp verification platform in Qatar",
    heroH1: "The Cheapest & First WhatsApp Gateway in Qatar & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Qatar.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP offers businesses in Qatar a fast, reliable and extremely affordable WhatsApp API solution for OTP and business messaging.",
    trustPoints: ["Excellent delivery across Qatar networks","Full Arabic & English support","Compliant with local regulations","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Qatar in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Qatar at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Qatari phone numbers +974?", answer: "Yes, it supports all Qatari numbers (+974) with high efficiency across Ooredoo and Vodafone Qatar." },
      { question: "How much does WhatsApp API cost in Qatar with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Qatar?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Qatar?", answer: "Yes, it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_QA",
      metaTitle: "WhatsApp API قطر | أرخص خدمة OTP واتساب في قطر $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في قطر: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل للشركات في الدوحة.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في قطر", heroH1: "أرخص وأول بوابة واتساب في قطر ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في قطر.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تقدم للشركات في قطر حلاً اقتصادياً وموثوقاً لإرسال OTP وإشعارات واتساب بتكامل سهل.",
      trustPoints: ["نسبة تسليم ممتازة داخل قطر","دعم عربي وإنجليزي كامل","متوافق مع اللوائح المحلية","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في قطر 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في قطر حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف القطرية +974؟", answer: "نعم، يدعم جميع أرقام قطر (+974) بكفاءة عالية عبر شبكات Ooredoo و Vodafone Qatar." },
        { question: "كم تكلفة WhatsApp API في قطر مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في قطر؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في قطر؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  jo: {
    countryName: "Jordan", countryCode: "JO", slug: "jo",
    locale: "ar_JO", language: "en", dir: "ltr",
    dialCode: "+962", geoPosition: "30.5852;36.2384",
    metaTitle: "WhatsApp API Jordan | أرخص WhatsApp OTP API في الأردن $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في الأردن. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +962. أفضل حل للشركات والمطورين الأردنيين.",
    metaKeywords: "whatsapp api jordan, whatsapp otp jordan, ارخص واتساب api الاردن, otp api الاردن, nabda otp jordan, whatsapp gateway jordan, twilio alternative jordan, whatsapp business api jordan, واتساب او تي بي الاردن",
    heroBadge: "The most reliable WhatsApp verification platform in Jordan",
    heroH1: "The Cheapest & First WhatsApp Gateway in Jordan & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Jordan.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides fast and affordable WhatsApp OTP solutions tailored for businesses and developers in Jordan with strong local delivery and Arabic support.",
    trustPoints: ["High delivery across Jordanian networks","Full Arabic support","Developer-friendly API","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Jordan in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Jordan at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Jordanian phone numbers +962?", answer: "Yes, it supports all Jordanian numbers (+962) with high efficiency and fast delivery across all networks." },
      { question: "How much does WhatsApp API cost in Jordan with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Jordan?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Jordan?", answer: "Yes, it saves up to 90% on costs with unlimited messages, instant webhook, and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text messages + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_JO",
      metaTitle: "WhatsApp API الأردن | أرخص خدمة OTP واتساب في الأردن $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في الأردن: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في الأردن", heroH1: "أرخص وأول بوابة واتساب في الأردن ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في الأردن.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين في الأردن على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة وتكامل سهل.",
      trustPoints: ["نسبة تسليم عالية داخل الأردن","دعم عربي كامل","API سهل للمطورين","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في الأردن 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في الأردن حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الأردنية +962؟", answer: "نعم، يدعم جميع أرقام الأردن (+962) بكفاءة عالية وتوصيل سريع عبر جميع الشبكات." },
        { question: "كم تكلفة WhatsApp API في الأردن مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في الأردن؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في الأردن؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة، webhook فوري، ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  sy: {
    countryName: "Syria", countryCode: "SY", slug: "sy",
    locale: "ar_SY", language: "en", dir: "ltr",
    dialCode: "+963", geoPosition: "34.8021;38.9968",
    metaTitle: "WhatsApp API Syria | أرخص WhatsApp OTP API في سوريا $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في سوريا. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +963. الحل الأمثل للشركات والمطورين السوريين.",
    metaKeywords: "whatsapp api syria, whatsapp otp syria, ارخص واتساب api سوريا, otp api سوريا, nabda otp syria, whatsapp gateway syria, twilio alternative syria, whatsapp business api syria, واتساب او تي بي سوريا, بوابة واتساب سوريا",
    heroBadge: "The most reliable WhatsApp verification platform in Syria",
    heroH1: "The Cheapest & First WhatsApp Gateway in Syria & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Syria.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Syrian businesses and developers with an affordable, fast, and reliable WhatsApp API solution for OTP and transactional messaging even in challenging network conditions.",
    trustPoints: ["Reliable delivery on Syrian networks","Optimized for local conditions","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Syria in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Syria at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Syrian phone numbers +963?", answer: "Yes, it supports all Syrian numbers (+963) with reliable delivery across available Syrian networks." },
      { question: "How much does WhatsApp API cost in Syria with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Syria?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Syria?", answer: "Yes, it is the most affordable alternative with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_SY",
      metaTitle: "WhatsApp API سوريا | أرخص خدمة OTP واتساب في سوريا $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في سوريا: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +963.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في سوريا", heroH1: "أرخص وأول بوابة واتساب في سوريا ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في سوريا.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين السوريين على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة جداً وتكامل سهل مع مراعاة الظروف المحلية.",
      trustPoints: ["توصيل موثوق على الشبكات السورية","مُحسّن للظروف المحلية","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في سوريا 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في سوريا حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف السورية +963؟", answer: "نعم، يدعم جميع أرقام سوريا (+963) بكفاءة عالية وتوصيل موثوق عبر الشبكات السورية." },
        { question: "كم تكلفة WhatsApp API في سوريا مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في سوريا؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في سوريا؟", answer: "نعم، هو أرخص بديل لـ Twilio في سوريا مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  kw: {
    countryName: "Kuwait", countryCode: "KW", slug: "kw",
    locale: "ar_KW", language: "en", dir: "ltr",
    dialCode: "+965", geoPosition: "29.3117;47.4818",
    metaTitle: "WhatsApp API Kuwait | أرخص WhatsApp OTP API في الكويت $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في الكويت. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +965. أفضل بديل لـ Twilio للشركات الكويتية.",
    metaKeywords: "whatsapp api kuwait, whatsapp otp kuwait, ارخص واتساب api الكويت, otp api الكويت, nabda otp kuwait, whatsapp gateway kuwait, twilio alternative kuwait, whatsapp business api kuwait, واتساب او تي بي الكويت",
    heroBadge: "The most reliable WhatsApp verification platform in Kuwait",
    heroH1: "The Cheapest & First WhatsApp Gateway in Kuwait & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Kuwait.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP helps businesses in Kuwait ship WhatsApp OTP and transactional messaging quickly with clean API workflows and high delivery rates.",
    trustPoints: ["High delivery across Kuwait networks","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Kuwait in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Kuwait at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Kuwaiti phone numbers +965?", answer: "Yes, it supports all Kuwaiti numbers (+965) with high efficiency and fast delivery." },
      { question: "How much does WhatsApp API cost in Kuwait with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Kuwait?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Kuwait?", answer: "Yes, it is the best alternative as it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_KW",
      metaTitle: "WhatsApp API الكويت | أرخص خدمة OTP واتساب في الكويت $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في الكويت: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +965.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في الكويت", heroH1: "أرخص وأول بوابة واتساب في الكويت ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في الكويت.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات في الكويت على إطلاق OTP وإشعارات واتساب بسرعة عالية مع تكامل API سلس وتوصيل موثوق.",
      trustPoints: ["نسبة تسليم عالية عبر شبكات الكويت","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في الكويت 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في الكويت حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الكويتية +965؟", answer: "نعم، يدعم جميع أرقام الكويت (+965) بكفاءة عالية وتوصيل سريع." },
        { question: "كم تكلفة WhatsApp API في الكويت مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في الكويت؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في الكويت؟", answer: "نعم، هو أفضل بديل لـ Twilio في الكويت لأنه يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  bh: {
    countryName: "Bahrain", countryCode: "BH", slug: "bh",
    locale: "ar_BH", language: "en", dir: "ltr",
    dialCode: "+973", geoPosition: "25.9304;50.6378",
    metaTitle: "WhatsApp API Bahrain | أرخص WhatsApp OTP API في البحرين $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في البحرين. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +973. أفضل حل للشركات و المطورين البحرينيين.",
    metaKeywords: "whatsapp api bahrain, whatsapp otp bahrain, ارخص واتساب api البحرين, otp api البحرين, nabda otp bahrain, whatsapp gateway bahrain, twilio alternative bahrain, whatsapp business api bahrain, واتساب او تي بي البحرين",
    heroBadge: "The most reliable WhatsApp verification platform in Bahrain",
    heroH1: "The Cheapest & First WhatsApp Gateway in Bahrain & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Bahrain.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP helps businesses in Bahrain launch fast and affordable WhatsApp OTP and transactional messaging with high delivery rates and full local support.",
    trustPoints: ["High delivery across Bahrain networks","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Bahrain in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Bahrain at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Bahraini phone numbers +973?", answer: "Yes, it supports all Bahraini numbers (+973) with fast and reliable delivery." },
      { question: "How much does WhatsApp API cost in Bahrain with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Bahrain?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Bahrain?", answer: "Yes, it saves up to 90% on costs with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_BH",
      metaTitle: "WhatsApp API البحرين | أرخص خدمة OTP واتساب في البحرين $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في البحرين: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +973.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في البحرين", heroH1: "أرخص وأول بوابة واتساب في البحرين ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في البحرين.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات في البحرين على إطلاق OTP وإشعارات واتساب بسرعة عالية مع تكامل API سلس وتوصيل موثوق.",
      trustPoints: ["نسبة تسليم عالية عبر شبكات البحرين","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في البحرين 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في البحرين حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف البحرينية +973؟", answer: "نعم، يدعم جميع أرقام البحرين (+973) بكفاءة عالية وتوصيل سريع." },
        { question: "كم تكلفة WhatsApp API في البحرين مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في البحرين؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في البحرين؟", answer: "نعم، هو أفضل بديل لـ Twilio في البحرين لأنه يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  om: {
    countryName: "Oman", countryCode: "OM", slug: "om",
    locale: "ar_OM", language: "en", dir: "ltr",
    dialCode: "+968", geoPosition: "21.4735;55.9754",
    metaTitle: "WhatsApp API Oman | أرخص WhatsApp OTP API في عمان $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في سلطنة عمان. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +968.",
    metaKeywords: "whatsapp api oman, whatsapp otp oman, ارخص واتساب api عمان, otp api عمان, nabda otp oman, whatsapp gateway oman, twilio alternative oman, whatsapp business api oman",
    heroBadge: "The most reliable WhatsApp verification platform in Oman",
    heroH1: "The Cheapest & First WhatsApp Gateway in Oman & MENA Region.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Oman.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Omani businesses with affordable and reliable WhatsApp messaging solutions.",
    trustPoints: ["Strong delivery in Oman","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Oman in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Oman at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Omani phone numbers +968?", answer: "Yes, it supports all Omani numbers (+968) with reliable delivery." },
      { question: "How much does WhatsApp API cost in Oman with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Oman?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Oman?", answer: "Yes, it offers up to 90% savings with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_OM",
      metaTitle: "WhatsApp API عمان | أرخص خدمة OTP واتساب في سلطنة عمان $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في عمان: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +968.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في عمان", heroH1: "أرخص وأول بوابة واتساب في عمان ومنطقة الشرق الأوسط وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في سلطنة عمان.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات في عمان على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة وتوصيل موثوق.",
      trustPoints: ["توصيل قوي داخل سلطنة عمان","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في عمان 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في سلطنة عمان حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف العمانية +968؟", answer: "نعم، يدعم جميع أرقام عمان (+968) بكفاءة عالية وتوصيل موثوق." },
        { question: "كم تكلفة WhatsApp API في عمان مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في عمان؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في عمان؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  lb: {
    countryName: "Lebanon", countryCode: "LB", slug: "lb",
    locale: "ar_LB", language: "en", dir: "ltr",
    dialCode: "+961", geoPosition: "33.8547;35.8623",
    metaTitle: "WhatsApp API Lebanon | أرخص WhatsApp OTP API في لبنان $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في لبنان. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +961.",
    metaKeywords: "whatsapp api lebanon, whatsapp otp lebanon, ارخص واتساب api لبنان, otp api لبنان, nabda otp lebanon, whatsapp gateway lebanon, twilio alternative lebanon",
    heroBadge: "The most reliable WhatsApp verification platform in Lebanon",
    heroH1: "The Cheapest & First WhatsApp Gateway in Lebanon.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Lebanon.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP offers Lebanese businesses a stable and affordable WhatsApp API solution.",
    trustPoints: ["Reliable delivery in Lebanon","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Lebanon in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Lebanon at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Lebanese phone numbers +961?", answer: "Yes, it supports all Lebanese numbers (+961) with reliable delivery despite local network conditions." },
      { question: "How much does WhatsApp API cost in Lebanon with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Lebanon?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Lebanon?", answer: "Yes, it provides significant cost savings with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_LB",
      metaTitle: "WhatsApp API لبنان | أرخص خدمة OTP واتساب في لبنان $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في لبنان: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +961.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في لبنان", heroH1: "أرخص وأول بوابة واتساب في لبنان.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في لبنان.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تقدم حلول واتساب اقتصادية ومستقرة للشركات اللبنانية.",
      trustPoints: ["توصيل موثوق داخل لبنان","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في لبنان 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في لبنان حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف اللبنانية +961؟", answer: "نعم، يدعم جميع أرقام لبنان (+961) بكفاءة عالية رغم الظروف الشبكية." },
        { question: "كم تكلفة WhatsApp API في لبنان مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في لبنان؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في لبنان؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  ma: {
    countryName: "Morocco", countryCode: "MA", slug: "ma",
    locale: "ar_MA", language: "en", dir: "ltr",
    dialCode: "+212", geoPosition: "31.7917;-7.0926",
    metaTitle: "WhatsApp API Morocco | أرخص WhatsApp OTP API في المغرب $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في المغرب. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +212.",
    metaKeywords: "whatsapp api morocco, whatsapp otp morocco, ارخص واتساب api المغرب, otp api المغرب, nabda otp morocco, whatsapp gateway morocco, whatsapp business api maroc",
    heroBadge: "The most reliable WhatsApp verification platform in Morocco",
    heroH1: "The Cheapest & First WhatsApp Gateway in Morocco & North Africa.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Morocco.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP serves Moroccan businesses with affordable and high-performance WhatsApp API solutions.",
    trustPoints: ["Strong delivery in Moroccan networks","Unlimited flat pricing","Full Arabic & French support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Morocco in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Morocco at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Moroccan phone numbers +212?", answer: "Yes, it supports all Moroccan numbers (+212) with high efficiency across Maroc Telecom, Orange, and Inwi." },
      { question: "How much does WhatsApp API cost in Morocco with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Morocco?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Morocco?", answer: "Yes, it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_MA",
      metaTitle: "WhatsApp API المغرب | أرخص خدمة OTP واتساب في المغرب $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في المغرب: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +212.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في المغرب", heroH1: "أرخص وأول بوابة واتساب في المغرب وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في المغرب.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تقدم للشركات المغربية حلول واتساب اقتصادية وموثوقة.",
      trustPoints: ["توصيل قوي عبر شبكات المغرب","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في المغرب 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في المغرب حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف المغربية +212؟", answer: "نعم، يدعم جميع أرقام المغرب (+212) بكفاءة عالية عبر شبكات Maroc Telecom، Orange و Inwi." },
        { question: "كم تكلفة WhatsApp API في المغرب مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في المغرب؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في المغرب؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  dz: {
    countryName: "Algeria", countryCode: "DZ", slug: "dz",
    locale: "ar_DZ", language: "en", dir: "ltr",
    dialCode: "+213", geoPosition: "28.0339;1.6596",
    metaTitle: "WhatsApp API Algeria | أرخص WhatsApp OTP API في الجزائر $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في الجزائر. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +213. الحل الأمثل للشركات والمطورين الجزائريين.",
    metaKeywords: "whatsapp api algeria, whatsapp otp algeria, ارخص واتساب api الجزائر, otp api الجزائر, nabda otp algeria, whatsapp gateway algeria, twilio alternative algeria, whatsapp business api algeria, واتساب او تي بي الجزائر",
    heroBadge: "The most reliable WhatsApp verification platform in Algeria",
    heroH1: "The Cheapest & First WhatsApp Gateway in Algeria & North Africa.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Algeria.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Algerian businesses with an affordable, fast and reliable WhatsApp API solution with strong local delivery.",
    trustPoints: ["Strong delivery across Algerian networks","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Algeria in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Algeria at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Algerian phone numbers +213?", answer: "Yes, it supports all Algerian numbers (+213) with high efficiency across Mobilis, Djezzy, and Ooredoo." },
      { question: "How much does WhatsApp API cost in Algeria with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Algeria?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Algeria?", answer: "Yes, it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_DZ",
      metaTitle: "WhatsApp API الجزائر | أرخص خدمة OTP واتساب في الجزائر $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في الجزائر: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +213.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في الجزائر", heroH1: "أرخص وأول بوابة واتساب في الجزائر وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في الجزائر.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين الجزائريين على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة وتوصيل موثوق عبر الشبكات الجزائرية.",
      trustPoints: ["توصيل قوي عبر الشبكات الجزائرية","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في الجزائر 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في الجزائر حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الجزائرية +213؟", answer: "نعم، يدعم جميع أرقام الجزائر (+213) بكفاءة عالية عبر شبكات Mobilis، Djezzy و Ooredoo." },
        { question: "كم تكلفة WhatsApp API في الجزائر مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في الجزائر؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في الجزائر؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  tn: {
    countryName: "Tunisia", countryCode: "TN", slug: "tn",
    locale: "ar_TN", language: "en", dir: "ltr",
    dialCode: "+216", geoPosition: "33.8869;9.5375",
    metaTitle: "WhatsApp API Tunisia | أرخص WhatsApp OTP API في تونس $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في تونس. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +216. الحل الأمثل للشركات والمطورين التونسيين.",
    metaKeywords: "whatsapp api tunisia, whatsapp otp tunisia, ارخص واتساب api تونس, otp api تونس, nabda otp tunisia, whatsapp gateway tunisia, twilio alternative tunisia, whatsapp business api tunisia, واتساب او تي بي تونس",
    heroBadge: "The most reliable WhatsApp verification platform in Tunisia",
    heroH1: "The Cheapest & First WhatsApp Gateway in Tunisia & North Africa.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Tunisia.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP helps Tunisian businesses launch fast and affordable WhatsApp OTP and transactional messaging with reliable delivery across local networks.",
    trustPoints: ["High delivery across Tunisian networks","Unlimited flat pricing","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Tunisia in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Tunisia at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Tunisian phone numbers +216?", answer: "Yes, it supports all Tunisian numbers (+216) with fast delivery across Orange, Tunisie Telecom, and Ooredoo." },
      { question: "How much does WhatsApp API cost in Tunisia with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Tunisia?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Tunisia?", answer: "Yes, it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_TN",
      metaTitle: "WhatsApp API تونس | أرخص خدمة OTP واتساب في تونس $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في تونس: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +216.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في تونس", heroH1: "أرخص وأول بوابة واتساب في تونس وشمال أفريقيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في تونس.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات التونسية على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة وتوصيل موثوق عبر الشبكات التونسية.",
      trustPoints: ["توصيل ممتاز عبر الشبكات التونسية","تسعير ثابت غير محدود","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في تونس 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في تونس حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف التونسية +216؟", answer: "نعم، يدعم جميع أرقام تونس (+216) بكفاءة عالية عبر شبكات Orange، Tunisie Telecom و Ooredoo." },
        { question: "كم تكلفة WhatsApp API في تونس مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في تونس؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في تونس؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  ly: {
    countryName: "Libya", countryCode: "LY", slug: "ly",
    locale: "ar_LY", language: "en", dir: "ltr",
    dialCode: "+218", geoPosition: "26.3351;17.2283",
    metaTitle: "WhatsApp API Libya | أرخص WhatsApp OTP API في ليبيا $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في ليبيا. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +218. الحل الأمثل للشركات والمطورين الليبيين.",
    metaKeywords: "whatsapp api libya, whatsapp otp libya, ارخص واتساب api ليبيا, otp api ليبيا, nabda otp libya, whatsapp gateway libya, twilio alternative libya, whatsapp business api libya, واتساب او تي بي ليبيا",
    heroBadge: "The most reliable WhatsApp verification platform in Libya",
    heroH1: "The Cheapest & First WhatsApp Gateway in Libya.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Libya.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Libyan businesses and developers with an affordable and reliable WhatsApp API solution adapted to local network conditions.",
    trustPoints: ["Reliable delivery on Libyan networks","Optimized for local conditions","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Libya in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Libya at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Libyan phone numbers +218?", answer: "Yes, it supports all Libyan numbers (+218) with reliable delivery across available networks." },
      { question: "How much does WhatsApp API cost in Libya with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Libya?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Libya?", answer: "Yes, it is the most affordable option with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_LY",
      metaTitle: "WhatsApp API ليبيا | أرخص خدمة OTP واتساب في ليبيا $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في ليبيا: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +218.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في ليبيا", heroH1: "أرخص وأول بوابة واتساب في ليبيا.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في ليبيا.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين الليبيين على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة مع مراعاة الظروف الشبكية المحلية.",
      trustPoints: ["توصيل موثوق على الشبكات الليبية","مُحسّن للظروف المحلية","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في ليبيا 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في ليبيا حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الليبية +218؟", answer: "نعم، يدعم جميع أرقام ليبيا (+218) بكفاءة عالية وتوصيل موثوق عبر الشبكات المتاحة." },
        { question: "كم تكلفة WhatsApp API في ليبيا مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في ليبيا؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في ليبيا؟", answer: "نعم، هو أرخص بديل لـ Twilio في ليبيا مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  ps: {
    countryName: "Palestine", countryCode: "PS", slug: "ps",
    locale: "ar_PS", language: "en", dir: "ltr",
    dialCode: "+970", geoPosition: "31.9522;35.2332",
    metaTitle: "WhatsApp API Palestine | أرخص WhatsApp OTP API في فلسطين $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في فلسطين. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +970. الحل الأمثل للشركات والمطورين الفلسطينيين.",
    metaKeywords: "whatsapp api palestine, whatsapp otp palestine, ارخص واتساب api فلسطين, otp api فلسطين, nabda otp palestine, whatsapp gateway palestine, twilio alternative palestine, whatsapp business api palestine, واتساب او تي بي فلسطين",
    heroBadge: "The most reliable WhatsApp verification platform in Palestine",
    heroH1: "The Cheapest & First WhatsApp Gateway in Palestine.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Palestine.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Palestinian businesses and developers with affordable and reliable WhatsApp messaging solutions adapted to local conditions.",
    trustPoints: ["Reliable delivery in Palestine","Optimized for local networks","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Palestine in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Palestine at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Palestinian phone numbers +970?", answer: "Yes, it supports all Palestinian numbers (+970) with reliable delivery." },
      { question: "How much does WhatsApp API cost in Palestine with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Palestine?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Palestine?", answer: "Yes, it saves up to 90% with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_PS",
      metaTitle: "WhatsApp API فلسطين | أرخص خدمة OTP واتساب في فلسطين $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في فلسطين: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +970.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في فلسطين", heroH1: "أرخص وأول بوابة واتساب في فلسطين.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في فلسطين.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين الفلسطينيين على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة وتوصيل موثوق.",
      trustPoints: ["توصيل موثوق داخل فلسطين","مُحسّن للظروف المحلية","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في فلسطين 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في فلسطين حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف الفلسطينية +970؟", answer: "نعم، يدعم جميع أرقام فلسطين (+970) بكفاءة عالية وتوصيل موثوق." },
        { question: "كم تكلفة WhatsApp API في فلسطين مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في فلسطين؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في فلسطين؟", answer: "نعم، يوفر حتى 90% من التكلفة مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  sd: {
    countryName: "Sudan", countryCode: "SD", slug: "sd",
    locale: "ar_SD", language: "en", dir: "ltr",
    dialCode: "+249", geoPosition: "12.8628;30.2176",
    metaTitle: "WhatsApp API Sudan | أرخص WhatsApp OTP API في السودان $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في السودان. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +249.",
    metaKeywords: "whatsapp api sudan, whatsapp otp sudan, ارخص واتساب api السودان, otp api السودان, nabda otp sudan, whatsapp gateway sudan, twilio alternative sudan, whatsapp business api sudan, واتساب او تي بي السودان",
    heroBadge: "The most reliable WhatsApp verification platform in Sudan",
    heroH1: "The Cheapest & First WhatsApp Gateway in Sudan.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Sudan.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP offers Sudanese businesses an affordable and reliable WhatsApp API solution with focus on local delivery.",
    trustPoints: ["Reliable delivery on Sudanese networks","Adapted to local conditions","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Sudan in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Sudan at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Sudanese phone numbers +249?", answer: "Yes, it supports all Sudanese numbers (+249) with reliable delivery across available networks." },
      { question: "How much does WhatsApp API cost in Sudan with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Sudan?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Sudan?", answer: "Yes, it is the most affordable option with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_SD",
      metaTitle: "WhatsApp API السودان | أرخص خدمة OTP واتساب في السودان $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في السودان: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +249.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في السودان", heroH1: "أرخص وأول بوابة واتساب في السودان.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في السودان.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات السودانية على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة مع مراعاة الظروف المحلية.",
      trustPoints: ["توصيل موثوق على الشبكات السودانية","مُحسّن للظروف المحلية","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في السودان 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في السودان حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف السودانية +249؟", answer: "نعم، يدعم جميع أرقام السودان (+249) بكفاءة عالية وتوصيل موثوق عبر الشبكات المتاحة." },
        { question: "كم تكلفة WhatsApp API في السودان مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في السودان؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في السودان؟", answer: "نعم، هو أرخص بديل لـ Twilio في السودان مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  ye: {
    countryName: "Yemen", countryCode: "YE", slug: "ye",
    locale: "ar_YE", language: "en", dir: "ltr",
    dialCode: "+967", geoPosition: "15.5527;48.5164",
    metaTitle: "WhatsApp API Yemen | أرخص WhatsApp OTP API في اليمن $10/شهر غير محدود | Nabda OTP",
    metaDescription: "Nabda OTP – أرخص WhatsApp API في اليمن. $10 شهرياً رسائل غير محدودة، بدون رسوم لكل رسالة، webhook، إرسال صور ومستندات، تجربة 5 أيام مجانية، دعم عربي كامل. يدعم أرقام +967.",
    metaKeywords: "whatsapp api yemen, whatsapp otp yemen, ارخص واتساب api اليمن, otp api اليمن, nabda otp yemen, whatsapp gateway yemen, twilio alternative yemen, whatsapp business api yemen, واتساب او تي بي اليمن",
    heroBadge: "The most reliable WhatsApp verification platform in Yemen",
    heroH1: "The Cheapest & First WhatsApp Gateway in Yemen.",
    heroSubtitle: "Send unlimited OTPs through our WhatsApp Gateway — Standard or Official API. The cheapest, most reliable API solution for developers and businesses in Yemen.",
    heroPriceNote: "Starting at just $10/month — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides Yemeni businesses with an affordable and reliable WhatsApp API solution adapted to local network conditions.",
    trustPoints: ["Reliable delivery on Yemeni networks","Adapted to local conditions","Full Arabic support","99.99% Uptime Guaranteed"],
    faq: [
      { question: "What is the cheapest WhatsApp API in Yemen in 2026?", answer: "Nabda OTP is currently the cheapest WhatsApp API in Yemen at only $10 per month for unlimited messages with no per-message fees." },
      { question: "Does Nabda OTP support Yemeni phone numbers +967?", answer: "Yes, it supports all Yemeni numbers (+967) with reliable delivery across available networks." },
      { question: "How much does WhatsApp API cost in Yemen with Nabda OTP?", answer: "The standard plan starts at just $10 per month (unlimited messages)." },
      { question: "Is there a free trial for WhatsApp API in Yemen?", answer: "Yes, a full 5-day free trial with no credit card or commitment required." },
      { question: "Is Nabda OTP a good alternative to Twilio in Yemen?", answer: "Yes, it is the most affordable option with unlimited messages and full Arabic support." },
      { question: "Does Nabda OTP support sending images, documents, and media?", answer: "Yes, it supports text + images + videos + PDF documents and more." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_YE",
      metaTitle: "WhatsApp API اليمن | أرخص خدمة OTP واتساب في اليمن $10/شهر غير محدود | Nabda OTP",
      metaDescription: "نبضة OTP في اليمن: واتساب API بـ 10 دولار شهرياً مع رسائل غير محدودة، ويبهوك، إرسال وسائط، تجربة مجانية 5 أيام، ودعم عربي كامل. يدعم أرقام +967.",
      heroBadge: "أقوى منصة تحقق عبر واتساب في اليمن", heroH1: "أرخص وأول بوابة واتساب في اليمن.", heroSubtitle: "أرسل عددًا غير محدود من رموز التحقق لمرة واحدة (OTP) عبر بوابة واتساب الخاصة بنا - واجهة برمجة التطبيقات القياسية أو الرسمية. الحل الأمثل والأكثر موثوقية للمطورين والشركات في اليمن.",
      heroPriceNote: "ابدأ من 10$ شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "نبضة OTP تساعد الشركات والمطورين اليمنيين على إطلاق OTP وإشعارات واتساب بتكلفة منخفضة مع مراعاة الظروف المحلية.",
      trustPoints: ["توصيل موثوق على الشبكات اليمنية","مُحسّن للظروف المحلية","دعم عربي كامل","توفر 99.99%"],
      faq: [
        { question: "ما هو أرخص WhatsApp API في اليمن 2026؟", answer: "نبضة OTP هو أرخص خدمة WhatsApp API في اليمن حالياً بـ 10 دولار فقط شهرياً مقابل رسائل غير محدودة." },
        { question: "هل Nabda OTP يدعم أرقام الهواتف اليمنية +967؟", answer: "نعم، يدعم جميع أرقام اليمن (+967) بكفاءة عالية وتوصيل موثوق عبر الشبكات المتاحة." },
        { question: "كم تكلفة WhatsApp API في اليمن مع Nabda OTP؟", answer: "تبدأ الخطة القياسية من 10 دولار شهرياً فقط (رسائل غير محدودة)." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في اليمن؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان أو التزام." },
        { question: "هل Nabda OTP بديل جيد لـ Twilio في اليمن؟", answer: "نعم، هو أرخص بديل لـ Twilio في اليمن مع رسائل غير محدودة ودعم عربي كامل." },
        { question: "هل يدعم Nabda OTP إرسال الصور والمستندات والوسائط؟", answer: "نعم، يدعم إرسال الرسائل النصية + الصور + الفيديوهات + المستندات PDF وغيرها بكل سهولة." },
      ],
    },
  },
  us: {
    countryName: "United States", countryCode: "US", slug: "us",
    locale: "en_US", language: "en", dir: "ltr",
    dialCode: "+1", geoPosition: "37.0902;-95.7129",
    metaTitle: "WhatsApp API USA | Cheap WhatsApp OTP API in United States $10/month Unlimited | Nabda OTP",
    metaDescription: "Nabda OTP – Affordable WhatsApp Gateway for the USA. $10/month unlimited messages, perfect for OTP, notifications, and transactional messaging. Easy integration and reliable delivery to US numbers.",
    metaKeywords: "whatsapp api usa, whatsapp otp usa, cheap whatsapp api united states, whatsapp gateway usa, twilio alternative usa, nabda otp usa",
    heroBadge: "Cost-effective WhatsApp solution for global businesses",
    heroH1: "The Cheapest WhatsApp Gateway in the United States.",
    heroSubtitle: "Send unlimited OTP and transactional messages to US numbers with flat monthly pricing and reliable delivery.",
    heroPriceNote: "Starting at just <strong>$10/month</strong> — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP offers developers and businesses in the USA a budget-friendly WhatsApp messaging solution with unlimited sending and strong reliability.",
    trustPoints: ["Works with US phone numbers","Unlimited messaging at flat rate","Easy developer API","99.99% Uptime"],
    faq: [
      { question: "Does Nabda OTP support US phone numbers (+1)?", answer: "Yes, it supports sending to United States numbers with good delivery rates for OTP and transactional messages." },
      { question: "What is the cheapest WhatsApp API for USA businesses?", answer: "Nabda OTP offers the most affordable option at just $10 per month for unlimited messages, unlike traditional providers that charge per message." },
      { question: "Is there a free trial for WhatsApp API in the USA?", answer: "Yes, enjoy a full 5-day free trial with no credit card required." },
      { question: "Can I send media and documents to US numbers?", answer: "Yes, supports text, images, videos, and document sending." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_US",
      metaTitle: "WhatsApp API الولايات المتحدة | أرخص واتساب أوتي بي API في أمريكا $10/شهر غير محدود | نبضة OTP",
      metaDescription: "نبضة OTP – بوابة واتساب اقتصادية في الولايات المتحدة. 10 دولار شهرياً رسائل غير محدودة، مثالية لرموز التحقق (OTP) والإشعارات والرسائل الخدمية. تكامل سهل وتوصيل موثوق للأرقام الأمريكية.",
      heroBadge: "حل واتساب اقتصادي للشركات العالمية", heroH1: "أرخص بوابة واتساب في الولايات المتحدة الأمريكية.", heroSubtitle: "أرسل عدد غير محدود من رموز التحقق OTP والرسائل الخدمية إلى الأرقام الأمريكية بسعر شهري ثابت وتوصيل موثوق.",
      heroPriceNote: "ابدأ من 10 دولار شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "تقدم نبضة OTP للمطورين والشركات في أمريكا حلاً اقتصادياً وموثوقاً لخدمات واتساب مع إرسال غير محدود.",
      trustPoints: ["يعمل مع الأرقام الأمريكية","رسائل غير محدودة بسعر ثابت","API سهل للمطورين","توفر 99.99%"],
      faq: [
        { question: "هل يدعم Nabda OTP الأرقام الأمريكية (+1)؟", answer: "نعم، يدعم إرسال الرسائل إلى الأرقام الأمريكية بمعدلات توصيل جيدة للـ OTP والرسائل الخدمية." },
        { question: "ما هو أرخص WhatsApp API للشركات في الولايات المتحدة؟", answer: "نبضة OTP هو الخيار الأرخص بـ 10 دولار شهرياً فقط مقابل رسائل غير محدودة." },
        { question: "هل يوجد تجربة مجانية لـ WhatsApp API في أمريكا؟", answer: "نعم، تجربة مجانية كاملة لمدة 5 أيام بدون بطاقة ائتمان." },
        { question: "هل يمكنني إرسال الصور والمستندات إلى الأرقام الأمريكية؟", answer: "نعم، يدعم إرسال النصوص + الصور + الفيديوهات + المستندات." },
      ],
    },
  },
  de: {
    countryName: "Germany", countryCode: "DE", slug: "de",
    locale: "de_DE", language: "en", dir: "ltr",
    dialCode: "+49", geoPosition: "51.1657;10.4515",
    metaTitle: "WhatsApp API Germany | Günstiger WhatsApp OTP API in Deutschland $10/Monat | Nabda OTP",
    metaDescription: "Nabda OTP – Günstiger WhatsApp Gateway für Deutschland. $10/Monat unbegrenzt Nachrichten, ideal für OTP und Transaktionsnachrichten.",
    metaKeywords: "whatsapp api deutschland, whatsapp otp germany, günstiger whatsapp api deutschland, whatsapp gateway germany, nabda otp germany",
    heroBadge: "Reliable & affordable for European markets",
    heroH1: "The Most Affordable WhatsApp API in Germany.",
    heroSubtitle: "Send unlimited OTP and transactional messages to German numbers with excellent delivery.",
    heroPriceNote: "Starting at just <strong>$10/month</strong> — No per-message fees",
    ctaPrimaryText: "Start Free Trial", ctaSecondaryText: "View Documentation",
    seoIntro: "Nabda OTP provides cost-effective WhatsApp solutions for businesses and developers targeting the German and DACH market.",
    trustPoints: ["Excellent delivery in Germany","Unlimited flat-rate messaging","Arabic & English support","99.99% Uptime"],
    faq: [
      { question: "Unterstützt Nabda OTP deutsche Telefonnummern (+49)?", answer: "Ja, es unterstützt Nummern aus Deutschland mit hoher Zustellrate für OTP und Benachrichtigungen." },
      { question: "Was kostet WhatsApp API in Deutschland?", answer: "Mit Nabda OTP nur 10 Dollar monatlich für unbegrenzte Nachrichten." },
      { question: "Gibt es eine kostenlose Testphase?", answer: "Ja, 5 Tage kostenlose Testphase ohne Kreditkarte." },
      { question: "Kann ich Bilder und Dokumente versenden?", answer: "Ja, vollständige Unterstützung für Medien und Dokumente." },
    ],
    ar: {
      language: "ar", dir: "rtl", locale: "ar_DE",
      metaTitle: "WhatsApp API ألمانيا | أرخص واتساب أوتي بي API في ألمانيا $10/شهر | نبضة OTP",
      metaDescription: "نبضة OTP – بوابة واتساب رخيصة في ألمانيا. 10 دولار شهرياً رسائل غير محدودة، مثالية للـ OTP والرسائل الخدمية مع توصيل ممتاز.",
      heroBadge: "موثوق واقتصادي للأسواق الأوروبية", heroH1: "أرخص واتساب API في ألمانيا.", heroSubtitle: "أرسل رسائل OTP وإشعارات غير محدودة إلى الأرقام الألمانية بتوصيل ممتاز وسعر شهري ثابت.",
      heroPriceNote: "ابدأ من 10 دولار شهرياً فقط — بدون رسوم لكل رسالة", ctaPrimaryText: "ابدأ التجربة المجانية", ctaSecondaryText: "عرض التوثيق",
      seoIntro: "تقدم نبضة OTP حلول واتساب اقتصادية وموثوقة للشركات والمطورين في ألمانيا وسوق DACH.",
      trustPoints: ["توصيل ممتاز في ألمانيا","رسائل غير محدودة بسعر ثابت","دعم عربي وإنجليزي","توفر 99.99%"],
      faq: [
        { question: "هل يدعم Nabda OTP الأرقام الألمانية (+49)؟", answer: "نعم، يدعم الأرقام الألمانية بمعدل توصيل عالي للـ OTP والإشعارات." },
        { question: "كم تكلفة WhatsApp API في ألمانيا مع Nabda OTP؟", answer: "10 دولار شهرياً فقط مقابل رسائل غير محدودة." },
        { question: "هل يوجد تجربة مجانية في ألمانيا؟", answer: "نعم، تجربة مجانية 5 أيام بدون بطاقة ائتمان." },
        { question: "هل يمكن إرسال الصور والمستندات؟", answer: "نعم، يدعم إرسال النصوص والصور والفيديوهات والمستندات." },
      ],
    },
  },
};

// Helper to get country + locale 
export function getCountryData(slug: string): CountryData | null {
  return COUNTRIES_DATA[slug] ?? null;
}

export function getCountryLocaleData(
  slug: string,
  locale: 'en' | 'ar' | 'tr'
): CountryLocaleData | null {
  const country = getCountryData(slug);
  if (!country) return null;
  if (locale === 'ar') return country.ar;
  if (locale === 'tr') return country.tr ?? null;
  // EN — map base country fields to locale data shape
  return {
    language:    country.language,
    dir:         country.dir,
    locale:      country.locale,
    metaTitle:   country.metaTitle,
    metaDescription: country.metaDescription,
    heroBadge:   country.heroBadge,
    heroH1:      country.heroH1,
    heroSubtitle: country.heroSubtitle,
    heroPriceNote: country.heroPriceNote,
    ctaPrimaryText: country.ctaPrimaryText,
    ctaSecondaryText: country.ctaSecondaryText,
    seoIntro:    country.seoIntro,
    trustPoints: country.trustPoints,
    faq:         country.faq,
  };
}

// All slugs for generateStaticParams
export const ALL_COUNTRY_SLUGS = [
  'eg','iq','sa','ae','qa','jo','sy','kw','bh','om',
  'lb','ma','dz','tn','ly','ps','sd','ye','us','de',
];

export const TURKEY_SLUG = 'turkey';